name: Sync from Gitea

on:
  repository_dispatch:
    types: [sync_gitea]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ vars.MY_REPO }}
        ref: ${{ vars.MY_BRANCH }}

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ vars.SSH_PORT }} -H ${{ vars.GITEA_HOST }} >> ~/.ssh/known_hosts
        echo -e "Host ${{ vars.GITEA_HOST }}\n  HostName ${{ vars.GITEA_HOST }}\n  IdentityFile ~/.ssh/id_rsa\n  Port ${{ vars.SSH_PORT }}\n" >> ~/.ssh/config

    - name: Add Gitea remote
      run: git remote add gitea ${{ vars.GITEA_URL }}

    - name: Fetch Gitea branch
      run: git fetch gitea ${{ vars.GITEA_BRANCH }}

    - name: Configure Git user
      run: |
        git config --global user.email "${{ vars.GIT_USER_EMAIL }}"
        git config --global user.name "${{ vars.GIT_USER_NAME }}"

    - name: Force merge Gitea branch
      run: |
        git checkout ${{ vars.MY_BRANCH }}
        git merge gitea/${{ vars.GITEA_BRANCH }} --allow-unrelated-histories --strategy-option theirs

    - name: Push changes to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin ${{ vars.MY_BRANCH }} --force
