name: Sync main branch from Gitea

on:
  schedule:
    - cron: '*/10 * * * *' # 每天午夜定时运行

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: hanckjt/hanckjt.github.io
        ref: master

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add Gitea remote
      run: git remote add gitea ssh://git@gitea.magictech.ai:222/hank/hanckjt.github.io.git

    - name: Fetch Gitea main branch
      run: git fetch gitea main

    - name: Merge Gitea main into master
      run: |
        git checkout master
        git merge gitea/main --allow-unrelated-histories

    - name: Push changes to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git push origin master
